const projectCards = [
  {
    id: 1,
    imageSrc: "/background-images/tablenow-homepage-image.png",
    date: "Jul 2023",
    title: "TABLENOW",
    description:
      "Tablenow is a real-time online reservation network web app for fine restaurants from different cities in Canada (Montreal, Ottawa and Niagara Region). It allows you to make online reservations and also read restaurant reviews from diners.",
    descriptionReverse:
      "A real-time online reservation network web app for fine restaurants from different cities in Canada (Montreal, Ottawa and Niagara Region). It allows you to make online reservations and also read restaurant reviews from diners.",
    github: "https://github.com/DanValMont/tablenow-restaurant-booking-web-app",
    website: "https://tablenow-nine.vercel.app/",
    roles: ["Brand Designer", "Web Designer", "Full-Stack Developer"],
    mainTechnologies: [
      "/icons/next-js.svg",
      "/icons/typescript.svg",
      "/icons/tailwindcss.svg",
      "/icons/materialui_icon.svg",
      "/icons/postgresql.svg",
      "/icons/JSON-Web-Token.svg",
      "/icons/prisma.svg",
      "/icons/supabase-logo-icon.svg",
    ],
    nameTechnologies: [
      "Next.js",
      "TypeScript",
      "Tailwind CSS",
      "Material UI",
      "PostgreSQL",
      "JWT",
      "Prisma",
      "Supabase",
    ],
  },
  {
    id: 2,
    imageSrc: "/background-images/pizza-mario-homepage-image.png",
    date: "March 2023",
    title: "PIZZA MARIO",
    description:
      "A beautiful, responsive and SEO optimized pizza ordering web application using next.js.",
    descriptionReverse:
      "A beautiful, responsive and SEO optimized pizza ordering web application using next.js.",
    github:
      "https://github.com/DanValMont/pizza-mario-pizza-a-pizza-ordering-web-app",
    website: "https://pizzamario.onrender.com/",
    roles: ["Brand Designer", "Web Designer", "Full-Stack Developer"],
    mainTechnologies: [
      "/icons/next-js.svg",
      "/icons/reactjs_icon.svg",
      "/icons/redux.svg",
      "/icons/react-chartjs-2.svg",
      "/icons/nodejs_icon.svg",
      "/icons/mongodb_logo_icon.svg",
      "/icons/mongoose_icon.svg",
      "/icons/paypal_icon.svg",
    ],
    nameTechnologies: [
      "Next.js",
      "React",
      "Redux",
      "React Chartjs",
      "Node.js",
      "MongoDB",
      "Mongoose",
      "Paypal API",
    ],
  },
  {
    id: 3,
    imageSrc: "/background-images/merged-homepage-image.png",
    date: "Nov 2022",
    title: "MERGED",
    description:
      "A chat and video call website app project, where you can talk with someone you know or talk with an anonymous random user. You have the possibility to screenshare and record and download the video calls.",
    descriptionReverse:
      "A chat and video call website app project, where you can talk with someone you know or talk with an anonymous random user. You have the possibility to screenshare and record and download the video calls.",
    github: "https://github.com/DanValMont/merged-video-call-chat-web-app",
    website: "https://merged.onrender.com/",
    roles: ["Brand Designer", "Web Designer", "Full-Stack Developer"],
    mainTechnologies: [
      "/icons/nodejs_icon.svg",
      "/icons/expressjs_icon.svg",
      "/icons/socket-io.svg",
      "/icons/webrtc.svg",
      "/icons/babel.svg",
      "/icons/webpack-icon.svg",
      "/icons/sass.svg",
    ],
    nameTechnologies: [
      "Node.js",
      "Express",
      "Socket.io",
      "WebRTC API",
      "Babel",
      "Webpack",
      "Sass",
    ],
  },
  {
    id: 4,
    imageSrc: "/background-images/2echo-homepage-image.png",
    date: "Aug 2022",
    title: "2ECHO",
    description:
      "A web application that allows anyone to post diverse ads and display them on an interactive, real-time map.",
    descriptionReverse:
      "A web application that allows anyone to post diverse ads and display them on an interactive, real-time map.",
    github:
      "https://github.com/DanValMont/2Echo-real-time-advertisement-web-app-on-an-interactive-map",
    website:
      "https://2-echo-real-time-advertisement-web-app-on-an-interactive-map.vercel.app/",
    roles: ["Brand Designer", "Web Designer", "Full-Stack Developer"],
    mainTechnologies: [
      "/icons/next-js.svg",
      "/icons/reactjs_icon.svg",
      "/icons/react-leaflet.svg",
      "/icons/materialui_icon.svg",
      "/icons/nodejs_icon.svg",
      "/icons/mongodb_logo_icon.svg",
      "/icons/mongoose_icon.svg",
      "/icons/JSON-Web-Token.svg",
    ],
    nameTechnologies: [
      "Next.js",
      "React",
      "React Leaflet",
      "Material UI",
      "Node.js",
      "MongoDB",
      "Mongoose",
      "JWT",
    ],
  },
  {
    id: 5,
    imageSrc: "/background-images/revelation-homepage-image.png",
    date: "Nov 2021",
    title: "REVELATION",
    description:
      "A professional, responsive and fully functional e-commerce website using Next.js framework.",
    descriptionReverse:
      "A professional, responsive and fully functional e-commerce website using Next.js framework.",
    github: "https://github.com/DanValMont/revelation-ecommerce-web-app",
    website: "https://revelation-ecommerce-web-app-3lc7.vercel.app/",
    roles: ["Brand Designer", "Web Designer", "Full-Stack Developer"],
    mainTechnologies: [
      "/icons/next-js.svg",
      "/icons/reactjs_icon.svg",
      "/icons/materialui_icon.svg",
      "/icons/nodejs_icon.svg",
      "/icons/mongodb_logo_icon.svg",
      "/icons/mongoose_icon.svg",
      "/icons/JSON-Web-Token.svg",
      "/icons/paypal_icon.svg",
    ],
    nameTechnologies: [
      "Next.js",
      "React",
      "Material UI",
      "Node.js",
      "MongoDB",
      "Mongoose",
      "JWT",
      "Paypal API",
    ],
  },
];

export default projectCards;
